[package]
name = "wmp"
version = "0.1.1"
edition = "2021"

[dependencies]
gstreamer = "0.23.1"
gtk = { version = "0.9.1", package = "gtk4", features =["v4_6"] }
mpris = "2.0.1"
serde_json = "1.0.128"
